### ISSUE TITLE
Floating Point Conversion - Bad data

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#29]
Examplse:
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '9.8589T437500'
Got error could not convert string to float: '9.8589T437500'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '16.829185S.616432'
Got error could not convert string to float: '16.829185S.616432'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 166, in _handleSerial
    millis = int(data[1],0)
ValueError: invalid literal for int() with base 0: '044327'
Got error invalid literal for int() with base 0: '044327'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 168, in _handleSerial
    press  = float(data[3])
ValueError: could not convert string to float: '21.78-05'
Got error could not convert string to float: '21.78-05'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '-19.911.422306'
Got error could not convert string to float: '-19.911.422306'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '119.094970.850012'
Got error could not convert string to float: '119.094970.850012'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 167, in _handleSerial
    count  = int(data[2],0)
ValueError: invalid literal for int() with base 0: ''
Got error invalid literal for int() with base 0: ''
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '-3.9711-3.902105'
Got error could not convert string to float: '-3.9711-3.902105'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 140, in _handleSerial
    onTime     = int(data[2],0)
ValueError: invalid literal for int() with base 0: '10.088485'
Got error invalid literal for int() with base 0: '10.088485'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '-UTATUS'
Got error could not convert string to float: '-UTATUS'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 168, in _handleSerial
    press  = float(data[3])
ValueError: could not convert string to float:
Got error could not convert string to float:
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '-31.78426938.407390'
Got error could not convert string to float: '-31.78426938.407390'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '25.30485.850997'
Got error could not convert string to float: '25.30485.850997'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '-2.6-7.180319'
Got error could not convert string to float: '-2.6-7.180319'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 168, in _handleSerial
    press  = float(data[3])
ValueError: could not convert string to float: '18.314.701781'
Got error could not convert string to float: '18.314.701781'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '-33.8.80947'
Got error could not convert string to float: '-33.8.80947'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 142, in _handleSerial
    state      = int(data[4],0)
IndexError: list index out of range
Got error list index out of range
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '-4.0-4.624879'
Got error could not convert string to float: '-4.0-4.624879'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 166, in _handleSerial
    millis = int(data[1],0)
ValueError: invalid literal for int() with base 0: '342.1309'
Got error invalid literal for int() with base 0: '342.1309'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '12.808069418.218116'
Got error could not convert string to float: '12.808069418.218116'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '-31.6916.282093'
Got error could not convert string to float: '-31.6916.282093'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '23.8118245.477775'
Got error could not convert string to float: '23.8118245.477775'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 170, in _handleSerial
    vol    = float(data[5])
ValueError: could not convert string to float: '6U625'
Got error could not convert string to float: '6U625'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 168, in _handleSerial
    press  = float(data[3])
ValueError: could not convert string to float: '21.5986.8'
Got error could not convert string to float: '21.5986.8'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 166, in _handleSerial
    millis = int(data[1],0)
ValueError: invalid literal for int() with base 0: '36197735821.461466244758'
Got error invalid literal for int() with base 0: '36197735821.461466244758'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '-4.857.947797'
Got error could not convert string to float: '-4.857.947797'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 168, in _handleSerial
    press  = float(data[3])
ValueError: could not convert string to float: '1U4033'
Got error could not convert string to float: '1U4033'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '-3.379324-6.199080'
Got error could not convert string to float: '-3.379324-6.199080'
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 169, in _handleSerial
    flow   = float(data[4])
ValueError: could not convert string to float: '-4.5854-10.039146'
Got error could not convert string to float: '-4.5854-10.039146'
Traceback (most recent call last):

**Comment by mwittgen** [comment]
This looks like scrambled data on the serial line. We are using 8N1. 8bit for text messages is not needed. We should switch to 7 bit with parity bit and also put a checksum on the message as well.
