### ISSUE TITLE
Python Startup Error

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#30]
This seems to happen every time:
base) C:\Users\mib\pabv_control\python_client>python client.py
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 0: invalid start byte
Got error 'utf-8' codec can't decode byte 0x98 in position 0: invalid start byte

**Comment by mwittgen** [comment]
There should be no printout  from a traceback when catching this exception.

**Comment by marty-pmr** [comment]
This happened at 1338 on Sunday:
(base) C:\Users\mib\pabv_control\python_client>python client.py
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 34: invalid continuation byte
Got error 'utf-8' codec can't decode byte 0xc2 in position 34: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 34: invalid continuation byte
Got error 'utf-8' codec can't decode byte 0xc2 in position 34: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 34: invalid continuation byte
Got error 'utf-8' codec can't decode byte 0xc2 in position 34: invalid continuation byte
