### ISSUE TITLE
Bug - Python stopped

### ISSUE THREAD

**Issue by marty-pmr** [slaclab/pabv_control#31]
![image](https://user-images.githubusercontent.com/63162118/82154587-b075aa00-9823-11ea-80a1-5e0de138595c.png)

**Comment by marty-pmr** [comment]
Stopped again. Is this relevant?:
 File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 1: invalid continuation byte
Got error 'utf-8' codec can't decode byte 0xc5 in position 1: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 1: invalid continuation byte
Got error 'utf-8' codec can't decode byte 0xc5 in position 1: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 1: invalid continuation byte
Got error 'utf-8' codec can't decode byte 0xc5 in position 1: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 12: invalid start byte
Got error 'utf-8' codec can't decode byte 0x9b in position 12: invalid start byte
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 0: invalid start byte
Got error 'utf-8' codec can't decode byte 0x8f in position 0: invalid start byte
Traceback (most recent call last):
  File "C:\Users\mib\pabv_control\python_client\ambu_control.py", line 126, in _handleSerial
    line = raw.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 0: invalid start byte
Got error 'utf-8' codec can't decode byte 0x8f in position 0: invalid start byte

**Comment by mwittgen** [comment]
This particular issue is fixed.
