### ISSUE TITLE
GUI Crash

### ISSUE THREAD

**Issue by bungernut** [slaclab/pabv_control#66]
There appears to be a bug associated with the clear alarms button running on the consolidate_branchs branch right now. 
```
Found USB-Serial at COM21
Traceback (most recent call last):
  File "C:\Users\bung\Documents\pabv_control\python_client\control_gui.py", line 731, in clearAlarm
    self.ambu.clearAlarm()
  File "C:\Users\bung\Documents\pabv_control\python_client\ambu_control.py", line 199, in clearAlarm
    m=Message.message()
NameError: name 'Message' is not defined

(base) C:\Users\bung\Documents\pabv_control\python_client>
```

**Comment by mwittgen** [comment]
Again I messed this up last night. Fixed now.
